#include <stdio.h>
#include <fcntl.h>
#include <unistd.h>
#include <sys/utsname.h>
#include <string.h>
#include <sys/types.h>
#include <sys/dir.h>
#include <time.h>
#include <sys/times.h>
#include <time.h>
#include <sys/wait.h>
#include <sys/stat.h>
#include <errno.h>
#include <signal.h>
#include <ctype.h>
#include <pwd.h>
#include <sys/resource.h>
#include <grp.h>
#include <stdlib.h>
#include <limits.h>
#include <termios.h>
#include "echo.h"
#include "prompt.h"
#include "cd.h"
#include "pwd.h"
#include "ls.h"
#include "pinfo.h"
#include "discover.h"
#include "history.h"
#include "jobs.h"
#include "sig.h"
#include "bg.h"
#include "fg.h"